export const NotificationTypes = {
    TICKET_CREATED: "TICKET_CREATED",
    TICKET_ASSIGNED: "TICKET_ASSIGNED",
    TICKET_STATUS_CHANGED: "TICKET_STATUS_CHANGED",
    TICKET_RESOLVED: "TICKET_RESOLVED",
    TICKET_CLOSED: "TICKET_CLOSED",
    NEW_COMMENT: "NEW_COMMENT",
    AI_REPLY_READY: "AI_REPLY_READY"
};